/* GENERATED by scripts/generate-archive-summary.mjs — do not edit.
   Run `npm run generate:summary` after changing archive data.

   The home page imports this instead of the full archive index so a first
   visit does not download every record's metadata in both languages. */

import type { ArchiveCategory, ArchiveLang } from './types'

export interface CoverageBand {
  /** Display name of the outlet. Absent on the academic row, whose label is
   *  translated in the UI like any other string. */
  outlet?: string
  academic?: boolean
  from: number
  to: number
  count: number
}

export interface PickSeed {
  id: string
  slug: string
  title: string
  date?: string
  outlet: string
  category: ArchiveCategory
}

export interface ArchiveSummary {
  counts: {
    columns: Record<ArchiveLang, number>
    analyses: number
    interviews: number
    academic: number
  }
  coverage: CoverageBand[]
  pickPool: Record<ArchiveLang, PickSeed[]>
}

export const archiveSummary: ArchiveSummary = {
  "counts": {
    "columns": {
      "tr": 474,
      "en": 97
    },
    "analyses": 7,
    "interviews": 5,
    "academic": 6
  },
  "coverage": [
    {
      "outlet": "Cumhuriyet",
      "from": 1982,
      "to": 1992,
      "count": 43
    },
    {
      "outlet": "Sabah",
      "from": 1993,
      "to": 1994,
      "count": 13
    },
    {
      "outlet": "Milliyet",
      "from": 1994,
      "to": 2001,
      "count": 127
    },
    {
      "outlet": "Zaman",
      "from": 2002,
      "to": 2013,
      "count": 244
    },
    {
      "outlet": "P24",
      "from": 2017,
      "to": 2024,
      "count": 47
    },
    {
      "outlet": "Today's Zaman",
      "from": 2007,
      "to": 2012,
      "count": 97
    },
    {
      "outlet": "Forum",
      "from": 1968,
      "to": 1968,
      "count": 2
    },
    {
      "outlet": "Aydınlık (Sosyalist Dergi/Proleter Devrimci)",
      "from": 1968,
      "to": 1970,
      "count": 4
    },
    {
      "outlet": "İşçi Köylü",
      "from": 1970,
      "to": 1970,
      "count": 1
    },
    {
      "academic": true,
      "from": 1980,
      "to": 2010,
      "count": 6
    }
  ],
  "pickPool": {
    "tr": [
      {
        "id": "columns-hocam-ve-dostum-tomas-hammara-veda",
        "slug": "hocam-ve-dostum-tomas-hammara-veda",
        "title": "Hocam ve dostum Tomas Hammar’a veda",
        "date": "1 Ağustos 2024",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-ergun-abiye-veda",
        "slug": "ergun-abiye-veda",
        "title": "“Ergun Abi”ye veda",
        "date": "9 Kasım 2023",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-ne-zaman-geleceksin",
        "slug": "ne-zaman-geleceksin",
        "title": "“Ne zaman geleceksin?”",
        "date": "10 Ekim 2023",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-bir-dostluk-hik-yesi",
        "slug": "bir-dostluk-hik-yesi",
        "title": "Bir dostluk hikâyesi",
        "date": "26 Ağustos 2023",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-fark-karizma-olabilir-mi",
        "slug": "fark-karizma-olabilir-mi",
        "title": "Fark, karizma olabilir mi?",
        "date": "13 Haziran 2023",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-manga-komutanima-veda",
        "slug": "manga-komutanima-veda",
        "title": "Manga komutanıma veda",
        "date": "8 Haziran 2023",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-ali-kemalin-fikirleri-degerini-koruyor",
        "slug": "ali-kemalin-fikirleri-degerini-koruyor",
        "title": "Ali Kemal’in fikirleri değerini koruyor",
        "date": "25 Nisan 2023",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-artik-bilelim-deprem-degil-bina-oldurur",
        "slug": "artik-bilelim-deprem-degil-bina-oldurur",
        "title": "Artık bilelim: Deprem değil, bina öldürür",
        "date": "16 Şubat 2023",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-buyukelcilikten-insan-haklari-savunuculuguna",
        "slug": "buyukelcilikten-insan-haklari-savunuculuguna",
        "title": "Büyükelçilikten insan hakları savunuculuğuna",
        "date": "15 Ocak 2023",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-stockholm-e-donus",
        "slug": "stockholm-e-donus",
        "title": "Stockholm’e Dönüş",
        "date": "2 Ocak 2023",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-gun-zileli-nin-anilari-uzerine",
        "slug": "gun-zileli-nin-anilari-uzerine",
        "title": "Gün Zileli’nin anıları üzerine",
        "date": "17 Ekim 2022",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-sevgili-dost-oblomov-erdala-veda",
        "slug": "sevgili-dost-oblomov-erdala-veda",
        "title": "Sevgili dost Oblomov Erdal’a veda",
        "date": "26 Mayıs 2022",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-bana-ne-lan-diyememek",
        "slug": "bana-ne-lan-diyememek",
        "title": "“Bana ne, lan!” diyememek",
        "date": "11 Nisan 2022",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-aydin-engin-anisina-saygi-ve-sukranlarimla",
        "slug": "aydin-engin-anisina-saygi-ve-sukranlarimla",
        "title": "Aydın Engin anısına saygı ve şükranlarımla",
        "date": "27 Mart 2022",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-hayat-hanimin-iki-yuzu",
        "slug": "hayat-hanimin-iki-yuzu",
        "title": "Hayat Hanım’ın iki yüzü",
        "date": "7 Mart 2022",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-harikalar-diyarinda",
        "slug": "harikalar-diyarinda",
        "title": "Harikalar diyarında",
        "date": "18 Aralık 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-kacik-radyoya-uzun-omurler",
        "slug": "kacik-radyoya-uzun-omurler",
        "title": "Kaçık Radyo’ya uzun ömürler",
        "date": "6 Aralık 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-kemalizmin-amaclanmayan-sonuclari",
        "slug": "kemalizmin-amaclanmayan-sonuclari",
        "title": "Kemalizmin amaçlanmayan sonuçları",
        "date": "14 Kasım 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-kurucu-felsefenin-esin-kaynaklari",
        "slug": "kurucu-felsefenin-esin-kaynaklari",
        "title": "“Kurucu felsefe”nin esin kaynakları",
        "date": "5 Kasım 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-darbecilikle-bogusurken-populizme-yakalanmak",
        "slug": "darbecilikle-bogusurken-populizme-yakalanmak",
        "title": "Darbecilikle boğuşurken popülizme yakalanmak",
        "date": "28 Eylül 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-assar-lindbeck-ve-liberal-sosyal-demokrasi",
        "slug": "assar-lindbeck-ve-liberal-sosyal-demokrasi",
        "title": "Assar Lindbeck ve liberal sosyal demokrasi",
        "date": "20 Eylül 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-yeni-dunya-gorusum",
        "slug": "yeni-dunya-gorusum",
        "title": "Yeni dünya görüşüm",
        "date": "19 Temmuz 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-kadri-bilinmemis-bir-sah-eser",
        "slug": "kadri-bilinmemis-bir-sah-eser",
        "title": "Kadri bilinmemiş bir şah-eser",
        "date": "6 Mayıs 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-trumpin-dunyaya-verdigi-dersler",
        "slug": "trumpin-dunyaya-verdigi-dersler",
        "title": "Trump’ın dünyaya verdiği dersler",
        "date": "28 Nisan 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-ne-umduk-ne-bulduk",
        "slug": "ne-umduk-ne-bulduk",
        "title": "Ne umduk, ne bulduk",
        "date": "17 Nisan 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-koronanin-da-isvec-modeli-var",
        "slug": "koronanin-da-isvec-modeli-var",
        "title": "Korona’nın da İsveç modeli var",
        "date": "30 Mart 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-bu-dunyadan-oguz-da-gecti",
        "slug": "bu-dunyadan-oguz-da-gecti",
        "title": "Bu dünyadan Oğuz da geçti",
        "date": "23 Mart 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-haluk-bekerin-ardindan",
        "slug": "haluk-bekerin-ardindan",
        "title": "Haluk Beker’in ardından",
        "date": "3 Şubat 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-gercekle-aramiz-hic-iyi-degil",
        "slug": "gercekle-aramiz-hic-iyi-degil",
        "title": "Gerçekle aramız hiç iyi değil",
        "date": "27 Ocak 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-2020-yilinda-turkiye",
        "slug": "2020-yilinda-turkiye",
        "title": "“2020 Yılında Türkiye”",
        "date": "8 Ocak 2020",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-vargas-llosanin-kesfi",
        "slug": "vargas-llosanin-kesfi",
        "title": "Vargas Llosa’nın keşfi",
        "date": "14 Aralık 2019",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-hayat-bir-mucize",
        "slug": "hayat-bir-mucize",
        "title": "Hayat bir mucize",
        "date": "29 Kasım 2019",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-cumhuriyet-demokrasi-ve-ozgurluk-iliskisi",
        "slug": "cumhuriyet-demokrasi-ve-ozgurluk-iliskisi",
        "title": "Cumhuriyet, demokrasi ve özgürlük ilişkisi",
        "date": "8 Kasım 2019",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-mirasi-siyasi-ozgurluk-ve-arkadaslik-uzerine",
        "slug": "mirasi-siyasi-ozgurluk-ve-arkadaslik-uzerine",
        "title": "Mirası siyasi özgürlük ve sosyal adalet için mücadele",
        "date": "23 Ekim 2019",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-fikirdaslik-ve-arkadaslik-uzerine",
        "slug": "fikirdaslik-ve-arkadaslik-uzerine",
        "title": "Fikirdaşlık ve arkadaşlık üzerine",
        "date": "2 Eylül 2019",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-komplo-teorisi-nedir-ne-degildir",
        "slug": "komplo-teorisi-nedir-ne-degildir",
        "title": "Komplo teorisi nedir, ne değildir",
        "date": "22 Ağustos 2019",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-fatma-ya-veda",
        "slug": "fatma-ya-veda",
        "title": "Fatma’ya veda",
        "date": "10 Ekim 2018",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-silivriden-sonra-ev-hapsinde",
        "slug": "silivriden-sonra-ev-hapsinde",
        "title": "Silivri’den sonra: Ev hapsinde",
        "date": "27 Mayıs 2018",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-dunyayi-guzellik-kurtaracak",
        "slug": "dunyayi-guzellik-kurtaracak",
        "title": "Dünyayı güzellik kurtaracak",
        "date": "16 Mart 2018",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-yalanda-yasamayi-reddetmek",
        "slug": "yalanda-yasamayi-reddetmek",
        "title": "Yalanda yaşamayı reddetmek",
        "date": "19 Şubat 2018",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-silivri-mektubu-ugradigim-haksizlik-son-bulmali",
        "slug": "silivri-mektubu-ugradigim-haksizlik-son-bulmali",
        "title": "Silivri Mektubu: Uğradığım haksızlık son bulmalı",
        "date": "23 Ocak 2018",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-anjiyo-oldum",
        "slug": "anjiyo-oldum",
        "title": "Anjiyo oldum",
        "date": "9 Ocak 2018",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-hayatin-ironisi",
        "slug": "hayatin-ironisi",
        "title": "Hayatın ironisi",
        "date": "25 Aralık 2017",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-silivri-mektubu-sagligim-gittikce-kotuluyor",
        "slug": "silivri-mektubu-sagligim-gittikce-kotuluyor",
        "title": "Silivri Mektubu: Sağlığım gittikçe kötülüyor",
        "date": "21 Kasım 2017",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-silivri-de-masumiyet-muzesi",
        "slug": "silivri-de-masumiyet-muzesi",
        "title": "Silivri’de “Masumiyet Müzesi”",
        "date": "7 Kasım 2017",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-silivri-mektubu-sagmalcilar-dan-silivri-ye",
        "slug": "silivri-mektubu-sagmalcilar-dan-silivri-ye",
        "title": "Silivri Mektubu: Sağmalcılar’dan Silivri’ye",
        "date": "26 Ekim 2017",
        "outlet": "P24",
        "category": "columns"
      },
      {
        "id": "columns-silivri-mektubu-hurriyet-denen-sey",
        "slug": "silivri-mektubu-hurriyet-denen-sey",
        "title": "Silivri mektubu: Hürriyet denen şey",
        "date": "3 Ekim 2017",
        "outlet": "P24",
        "category": "columns"
      }
    ],
    "en": []
  }
}
