/* GENERATED by scripts/generate-archive-summary.mjs — do not edit.
   Run `npm run generate:summary` after changing archive data.

   The home page imports this instead of the full archive index so a first
   visit does not download every record's metadata in both languages. */

import type { ArchiveLang } from './types'

export interface CoverageBand {
  /** Display name of the outlet. Absent on the academic row, whose label is
   *  translated in the UI like any other string. */
  outlet?: string
  academic?: boolean
  from: number
  to: number
  count: number
}

export interface ArchiveSummary {
  counts: {
    columns: Record<ArchiveLang, number>
    analyses: number
    interviews: number
    academic: number
  }
  coverage: CoverageBand[]
}

export const archiveSummary: ArchiveSummary = {
  "counts": {
    "columns": {
      "tr": 477,
      "en": 97
    },
    "analyses": 1,
    "interviews": 8,
    "academic": 29
  },
  "coverage": [
    {
      "outlet": "Cumhuriyet",
      "from": 1982,
      "to": 1992,
      "count": 43
    },
    {
      "outlet": "Sabah",
      "from": 1993,
      "to": 1994,
      "count": 13
    },
    {
      "outlet": "Milliyet",
      "from": 1994,
      "to": 2001,
      "count": 127
    },
    {
      "outlet": "Zaman",
      "from": 2002,
      "to": 2013,
      "count": 244
    },
    {
      "outlet": "P24",
      "from": 2017,
      "to": 2024,
      "count": 47
    },
    {
      "outlet": "Medyascope",
      "from": 2025,
      "to": 2026,
      "count": 3
    },
    {
      "outlet": "Today's Zaman",
      "from": 2007,
      "to": 2012,
      "count": 97
    },
    {
      "outlet": "İşçi Köylü",
      "from": 1970,
      "to": 1970,
      "count": 1
    },
    {
      "academic": true,
      "from": 1982,
      "to": 2011,
      "count": 29
    }
  ]
}
