/** A book's own foreword, shown in a dialog on the Books page. The text is
 *  the author's, in the book's language (Turkish), and is shown untranslated
 *  on the English page too — never machine-translated. */
export interface BookForeword {
  paragraphs: string[]
}

/* Bir Hikâyem Var (2024), “Önsöz” — as supplied by the owner on 2026-10-08.
   Only a missing space (“geçirdiğimizyaklaşık”) was corrected. */
export const birHikayemVarForeword: BookForeword = {
  paragraphs: [
    'Gabriel Garcia Marquez, biyografisini kaleme alan Gerald Martin\'e şöyle demiş: "Her birimizin üç ayrı hayatı vardır; kamusal, özel ve gizli hayatlarımız..." Özel ile kamusal hayat ayrımının ziyadesiyle bilincinde oldum, çünkü hayatım bu ikisi arasındaki gerginlik üzerinde şekillendi. Şimdi okumaya başlayacağınız anılarım da bu gerginliğin mihverinde yaşadıklarımın öyküsünden ibaret. Gizli hayatımın özel hayatımın ayrılmaz bir parçası olduğunu düşünüyor ve onu da, ne kadarı mümkünse anlatmayı umuyorum.',
    'Fatma, benim özel, kamusal ve gizli tüm hayatımın başkahramanıydı. Her üç hayatımda da en büyük rol hep ona ait oldu. Ünlü İngiliz romancı Iris Murdoch, ilk romanında, "Hiç tükenmeyen birini bulmak, aşkın en yalın tanımıdır” diye yazmış. Fatma benim hiç tükenmeyen, aksine giderek büyüyen aşkım oldu. Hayatımı Fatma\'ya demirli olarak yaşadığım için, tanıdığım en şanslı insan benim. Kendimi en mutlu hissettiğim günlerde ona, "Fatmacım, sen bana yeryüzünde cenneti yaşattın!" dediğimde en içten duygularımı dile getiriyordum.',
    'Fatma da hayatını bana demirli olarak yaşamayı seçti; özel, kamusal ve gizli hayatını benimle paylaştı. Buna pişman oldu mu? Evet, zaman zaman... Hiç şüphem yok ki o daha yaşanmaya değer, daha az sıkıntı, üzüntü ve acı çektiği bir hayata layıktı. Eminim ki sevdiği bir meslek sahibi olmak fırsatını bulsaydı, hayatı bana demirli olmayabilir, daha mutlu bir yaşam sürebilirdi... Hep söylediği gibi, belki kızımız Elvan uğruna beni terketmedi... Ona duyduğum aşkı ölümsüz kılan unsurlardan belki biri de hiçbir zaman sevgisinden emin olmayışımdı. Bana olan bağlılığını davranışlarıyla gösterdi.',
    'Fatma\'yla 55 yıl süren ortak bir hayat yaşadık. Bu yüzden kitabın adını Fatma\'yla Hayatım koymayı düşünmedim değil. Fakat ne kadar çok şeyi paylaşsak da, bu benim hayat hikâyem. Beş yılını zorunlu olarak ondan ayrı geçirdiğim 55 yıllık beraberliğimiz, hiç beklenmedik bir şekilde, 6 Ekim 2018\'de Fatmam\'ın benim 60 yıllık dostum, onun 20 yıllık doktoru Prof. Dr. Hasan Yazıcı\'nın muayenehanesinde beyin kanaması geçirerek aniden veda etmesiyle son buldu. Silivri cezaevinden tahliye olmamdan sonra birlikte geçirdiğimiz yaklaşık son altı ay içinde artık geriye hiç bakmayacağımıza, geçmişin sözünü etmeyeceğimize, kalan yıllarımızı sadece birbirimizi düşünerek yaşayacağımıza karar vermiştik. Nasip değilmiş... Ayvalık\'ta birlikte geçirdiğimiz son günlerde, İstanbul\'a dönünce bana beni anlatmaya söz vermişti. O da nasip olmadı. Dolayısıyla ne yazık ki okuyacağınız bu anılar çok eksik kaldı.',
    'Yazılmaya değer bir hayat yaşadığıma inanıyorum. Bunun temel sebebi, ergen hayatımın hemen tamamını, tanıdığım en güzel kadın ve en kusursuz insan olan Fatma\'yla geçirmiş olmam. Fatma akıllı, sağduyulu, duyarlı, gerçekçi, ayağı yere basan, serinkanlı, dirayet sahibi, dürüst, içten, özgüvenli, onurlu, tek kelimeyle soylu karakteriyle bana çok şey kazandırdı; beni ben yapan iki kadından biri, annemden de çok o\'ydu. Ona çok şey borçluyum; her şeyden önce yetiştirdiği pırlanta çocuklarım Elvan ve Acar\'ı, pırlanta torunlarım Defne ve Leyla\'yı...',
    'Fatma\'yı toprağa verdiğimiz 10 Ekim 2018 günü onun Çamlık\'taki evinin terasında, acımı paylaşmaya gelen yakın arkadaşlarımla bir masanın etrafında toplandık. "Türkiye\'nin bu hale geleceğini öngörebilmiş olsaydım, hayatımı çok başka türlü yaşardım," dedim. Bunun bir hamhayal olduğunu bilmiyor değildim, ama ifade etmek istediğim şuydu: Başa dönebilseydim hayatımı bütünüyle Fatma\'ya adardım. Onun gibi ben de iki değil dört çocuğumuz olsun isterdim; ondan değil beş yıl, bir gün bile ayrı kalmazdım. Masadaki dostlarımdan Nuri Çolakoğlu\'nun tepkisi şu oldu: "Niye öyle diyorsun yaa!.. Anılarını yazıyorsun. Bitirdiğinde, kitaba bakıp \'Ne hayat yaşamışım be!\' diyeceksin..." Bilmiyorum öyle olacak mı, ama şurası muhakkak: Anılarımı kendim ve Fatma için; onun beni ne kadar mutlu ettiğini; benim onu mutlu etmede ne kadar aciz kaldığımı; onunla paylaştıklarımızı kayda geçirmek için, herkesten önce çocuklarım ve torunlarım için yazıyorum. Anılarım, yaşadığım uzunca dönemin yurt ve dünya siyasetinin tanıklığını yapma amacını gütmüyor; sadece bunların benim hayatım üzerindeki etkilerini anlatıyor.',
    'Evet, bu kitabın adını Fatma\'yla Hayatım koyabilirdim. Fakat onunla ne kadar çok şeyi paylaşsak da, bu benim hayat hikâyem... Geçenlerde bir gün Fatma\'nın yeğeni, rahmetli baldızım Ayşe\'nin oğlu Cenk ile sohbet ederken, "Enişte senin bir hikâyen var...  Ben de bir hikâyem olsun isterdim..." dedi. Ondan esinlenerek anılarıma Bir hikâyem var başlığını vermeye karar verdim.',
  ],
}

/* Hikâyemin Sonu (2025), “Önsöz” — as supplied by the owner on 2026-10-08,
   unedited. */
export const hikayeminSonuForeword: BookForeword = {
  paragraphs: [
    '21. yüzyılın başlarına gelindiğinde ev ve iş hayatıma esenlik hakim olmuştu. Çeşitli rahatsızlıklarına rağmen eşim Fatma\'nın sağlığı genelde iyi olduğu gibi keyfi de yerindeydi. Ressam olarak verdiği eserlerden gurur duyduğumuz kızımız Elvan evlenmiş ve bize çok sevdiğimiz torunumuz Defne\'yi kazandırmıştı. Oğlumuz Acar yüksek öğrenimi başarıyla tamamlayarak, grafik tasarımcı kariyerine adım atmıştı. Ben meslek hayatımda o zamana kadar hiç olmadığı kadar görünür olmuştum. Tam-zaman çalıştığım Bahçeşehir Üniversitesi\'nde siyaset bilimi dersleri verirken, Zaman gazetesine dışarıdan köşe yazıları yazıyor, dostlarım Eser Karakaş ve Mehmet Altan ile birlikte Mehtap - TV\'de haftalık bir yorum programı yapıyordum. Hayatımdan memnundum.',
    'Ülkemin ve dünyanın geleceğine dair iyimserliğim adeta tavan yapmıştı. Kasım 2002\'de iktidara gelen Adalet ve Kalkınma Partisi (bundan böyle AKP) iktidarı, özgürlükçü demokratik rejimi ve piyasa ekonomisini yerleştirerek Türkiye\'yi AB üyesi yapmayı vadediyordu. Dünyada barış, demokratikleşme ve zenginleşme çağı yaşanıyordu. Ne var ki çok geçmeden ülkemle ve dünyayla ilgili iyimserliğim sarsılacaktı. AKP iktidarı uyandırdığı umutlara ters yönde yol almaya başladı; vaadlerinden giderek uzaklaştı. Derken bütün dünyada kaygı veren gelişmeler yaşanır oldu; özgürlükçü demokrasiyi yerleştirmiş olduğuna inanılan ülkelerde dahi popülizm ve otoriterleşme eğilimleri kendini belli eder oldu. 21. yüzyılın kabaca ilk on yılını geride bıraktığımızda önce ülkenin, sonra da dünyanın geleceği hakkındaki iyimserliğim yerini giderek artan bir karamsarlığa bırakmıştı.',
    'AKP iktidarı AB üyeliği hedefinden uzaklaşmaya koşut olarak rekabetçi bir piyasa ekonomisinin inşası yerine devlet müdahalelerinin giderek arttığı bir ekonomik düzen kurmaya yöneldi. Kürt kökenli yurttaşların kimlik, dil ve kültür haklarının tanınma taleplerinin karşılanmasında pek az yol alındı. Rejim giderek, iktidarın seçimle belirlendiği ancak temel hak ve özgürlüklerin giderek daha kısıtlandığı bir çoğunluk diktatörlüğüne benzedi. Bu gelişmeler ışığında AKP iktidarına bakışım değişti. Başlangıçtaki hem destek - hem eleştiri ilkelerine dayalı yaklaşım yerini giderek sertleşen eleştirel bakışa bıraktı.',
    'İktidar ile muhalefet arasında giderek gerginleşen ilişkiler meslek hayatımda da olumsuz gelişmelere yol açtı. 2015 sonbaharında 14 yıldır görev yaptığım Bahçeşehir Üniversitesi\'ndeki işime son verildi. Mart 2016\'da köşe yazdığım Zaman gazetesi yönetimine kayyım atandı. 15 Temmuz 2016\'da Zaman gazetesini çıkarmakta olan Fethullah Gülen cemaatinin sorumlu tutulduğu, fakat henüz sorumluları hakkında tam bir aydınlığa kavuşulmamış olan bir askeri darbe girişimi yaşandı. Girişim sırasında Ankara\'da meclis binası jet uçakları tarafından bombalandı; İstanbul\'da Boğaziçi Köprüsü üzerinde askerlerle siviller arasında çıkan çatışmalarda 250\'den fazla yurttaş hayatını kaybetti. Darbe girişiminin bastırılmasını takiben Gülen cemaatiyle ilişkili onbinlerce kişi tutuklanarak cezaevlerine konuldu. Herhangi bir dinsel cemaatle herhangi bir fikri ya da örgütsel ilişkim söz konusu olmadığı; darbe girişiminden bir gün önce yayımlanan köşe yazımda hemen bütün yazarlık hayatım boyunca yaptığım gibi askeri darbe girişimlerine karşı olduğumu belirttiğim halde 27 Temmuz 2016\'da gözaltına alındım; 31 Temmuz\'da tutuklanarak Silivri (yeni adıyla Marmara) Cezaevi\'ne gönderildim.',
    'Anılarımın bu ikinci kitabında, Bahçeşehir Üniversitesi\'nde tam-zaman öğretim üyeliği yaparken Zaman gazetesine köşe yazıları yazdığım 2001\'den 2015\'e uzanan dönemde başımdan geçenleri; 15 Temmuz darbe girişimini takiben tutuklanarak hapsedilmeme gerek yurt içinden gerekse dışından gelen tepkileri; yargılanma sürecimi; tuttuğum günceye yansıyan hapishane anılarımı ve cezaevinden tahliye edilmemden sonra sevgilim ve eşim Fatma\'yla ömrünün son altı ayında birlikte yaşadıklarımızı okuyacaksınız. Kitabın Zaman anılarımla ilgili bölümünde, gazetenin arşivi ulaşılamaz durumda olduğu için kimi yazılarımdan kimi geniş alıntılar bulacaksınız.',
    'Başka vesilelerle de belirttiğim gibi, Fatma\'yla birlikte geçirdiğim 55 yıl benim gerçek hayatımdır. Onu toprağa verdiğimiz 10 Ekim 2018 günü yakın arkadaşlarıma, Fatma\'yla birlikte yaşadıklarımızı yazdıktan sonra ölmeye hazır olacağımı söylemiştim. Başımdan geçenleri yazmak ve yayınlamak imkanını bulduğum için mutluyum. Anılarımın basımını üstlenen Lejand Yayınları\'na teşekkür borçluyum.',
  ],
}
