/** A book's own foreword, shown in a dialog on the Books page. The text is
 *  the author's, in the book's language (Turkish), and is shown untranslated
 *  on the English page too — never machine-translated. */
export interface BookForeword {
  paragraphs: string[]
}

/* Bir Hikâyem Var (2024), “Önsöz” — as supplied by the owner on 2026-10-08.
   Only a missing space (“geçirdiğimizyaklaşık”) was corrected. */
export const birHikayemVarForeword: BookForeword = {
  paragraphs: [
    'Gabriel Garcia Marquez, biyografisini kaleme alan Gerald Martin\'e şöyle demiş: "Her birimizin üç ayrı hayatı vardır; kamusal, özel ve gizli hayatlarımız..." Özel ile kamusal hayat ayrımının ziyadesiyle bilincinde oldum, çünkü hayatım bu ikisi arasındaki gerginlik üzerinde şekillendi. Şimdi okumaya başlayacağınız anılarım da bu gerginliğin mihverinde yaşadıklarımın öyküsünden ibaret. Gizli hayatımın özel hayatımın ayrılmaz bir parçası olduğunu düşünüyor ve onu da, ne kadarı mümkünse anlatmayı umuyorum.',
    'Fatma, benim özel, kamusal ve gizli tüm hayatımın başkahramanıydı. Her üç hayatımda da en büyük rol hep ona ait oldu. Ünlü İngiliz romancı Iris Murdoch, ilk romanında, "Hiç tükenmeyen birini bulmak, aşkın en yalın tanımıdır” diye yazmış. Fatma benim hiç tükenmeyen, aksine giderek büyüyen aşkım oldu. Hayatımı Fatma\'ya demirli olarak yaşadığım için, tanıdığım en şanslı insan benim. Kendimi en mutlu hissettiğim günlerde ona, "Fatmacım, sen bana yeryüzünde cenneti yaşattın!" dediğimde en içten duygularımı dile getiriyordum.',
    'Fatma da hayatını bana demirli olarak yaşamayı seçti; özel, kamusal ve gizli hayatını benimle paylaştı. Buna pişman oldu mu? Evet, zaman zaman... Hiç şüphem yok ki o daha yaşanmaya değer, daha az sıkıntı, üzüntü ve acı çektiği bir hayata layıktı. Eminim ki sevdiği bir meslek sahibi olmak fırsatını bulsaydı, hayatı bana demirli olmayabilir, daha mutlu bir yaşam sürebilirdi... Hep söylediği gibi, belki kızımız Elvan uğruna beni terketmedi... Ona duyduğum aşkı ölümsüz kılan unsurlardan belki biri de hiçbir zaman sevgisinden emin olmayışımdı. Bana olan bağlılığını davranışlarıyla gösterdi.',
    'Fatma\'yla 55 yıl süren ortak bir hayat yaşadık. Bu yüzden kitabın adını Fatma\'yla Hayatım koymayı düşünmedim değil. Fakat ne kadar çok şeyi paylaşsak da, bu benim hayat hikâyem. Beş yılını zorunlu olarak ondan ayrı geçirdiğim 55 yıllık beraberliğimiz, hiç beklenmedik bir şekilde, 6 Ekim 2018\'de Fatmam\'ın benim 60 yıllık dostum, onun 20 yıllık doktoru Prof. Dr. Hasan Yazıcı\'nın muayenehanesinde beyin kanaması geçirerek aniden veda etmesiyle son buldu. Silivri cezaevinden tahliye olmamdan sonra birlikte geçirdiğimiz yaklaşık son altı ay içinde artık geriye hiç bakmayacağımıza, geçmişin sözünü etmeyeceğimize, kalan yıllarımızı sadece birbirimizi düşünerek yaşayacağımıza karar vermiştik. Nasip değilmiş... Ayvalık\'ta birlikte geçirdiğimiz son günlerde, İstanbul\'a dönünce bana beni anlatmaya söz vermişti. O da nasip olmadı. Dolayısıyla ne yazık ki okuyacağınız bu anılar çok eksik kaldı.',
    'Yazılmaya değer bir hayat yaşadığıma inanıyorum. Bunun temel sebebi, ergen hayatımın hemen tamamını, tanıdığım en güzel kadın ve en kusursuz insan olan Fatma\'yla geçirmiş olmam. Fatma akıllı, sağduyulu, duyarlı, gerçekçi, ayağı yere basan, serinkanlı, dirayet sahibi, dürüst, içten, özgüvenli, onurlu, tek kelimeyle soylu karakteriyle bana çok şey kazandırdı; beni ben yapan iki kadından biri, annemden de çok o\'ydu. Ona çok şey borçluyum; her şeyden önce yetiştirdiği pırlanta çocuklarım Elvan ve Acar\'ı, pırlanta torunlarım Defne ve Leyla\'yı...',
    'Fatma\'yı toprağa verdiğimiz 10 Ekim 2018 günü onun Çamlık\'taki evinin terasında, acımı paylaşmaya gelen yakın arkadaşlarımla bir masanın etrafında toplandık. "Türkiye\'nin bu hale geleceğini öngörebilmiş olsaydım, hayatımı çok başka türlü yaşardım," dedim. Bunun bir hamhayal olduğunu bilmiyor değildim, ama ifade etmek istediğim şuydu: Başa dönebilseydim hayatımı bütünüyle Fatma\'ya adardım. Onun gibi ben de iki değil dört çocuğumuz olsun isterdim; ondan değil beş yıl, bir gün bile ayrı kalmazdım. Masadaki dostlarımdan Nuri Çolakoğlu\'nun tepkisi şu oldu: "Niye öyle diyorsun yaa!.. Anılarını yazıyorsun. Bitirdiğinde, kitaba bakıp \'Ne hayat yaşamışım be!\' diyeceksin..." Bilmiyorum öyle olacak mı, ama şurası muhakkak: Anılarımı kendim ve Fatma için; onun beni ne kadar mutlu ettiğini; benim onu mutlu etmede ne kadar aciz kaldığımı; onunla paylaştıklarımızı kayda geçirmek için, herkesten önce çocuklarım ve torunlarım için yazıyorum. Anılarım, yaşadığım uzunca dönemin yurt ve dünya siyasetinin tanıklığını yapma amacını gütmüyor; sadece bunların benim hayatım üzerindeki etkilerini anlatıyor.',
    'Evet, bu kitabın adını Fatma\'yla Hayatım koyabilirdim. Fakat onunla ne kadar çok şeyi paylaşsak da, bu benim hayat hikâyem... Geçenlerde bir gün Fatma\'nın yeğeni, rahmetli baldızım Ayşe\'nin oğlu Cenk ile sohbet ederken, "Enişte senin bir hikâyen var...  Ben de bir hikâyem olsun isterdim..." dedi. Ondan esinlenerek anılarıma Bir hikâyem var başlığını vermeye karar verdim.',
  ],
}
